name: 打包应用并上传阿里云

on:
    push:
        branches:
            - master
    workflow_dispatch:  # 添加手动触发支持

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境
        runs-on: ubuntu-latest
        steps:
            # 获取源码
            - name: 迁出代码
              uses: actions/checkout@v3  # 使用v3版本，推荐使用稳定版本

            # 设置Bun
            - name: 设置Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            # 安装应用依赖
            - name: 安装应用依赖
              run: bun install

            # 打包应用
            - name: 打包应用
              run: bun run build
              
            # 上传到阿里云
            - name: 发布到阿里云
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}  # SSH 密钥
                  ARGS: '-avzr --delete --exclude=.user.ini'  # Rsync 参数
                  SOURCE: '.output/'  # 源目录
                  REMOTE_HOST: ${{ secrets.SERVER_HOST }}  # 服务器地址
                  REMOTE_USER: 'root'  # 用户名
                  TARGET: '/www/wwwroot/nuxt'  # 目标路径，注意这里应该是一个有效的路径